# Generated by Django 6.0.4 on 2026-07-21 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_colegio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='rol',
            field=models.CharField(choices=[('ADMINISTRADOR', 'Administrador / Secretaría'), ('PROFESOR', 'Profesor / Docente'), ('DIRECTOR', 'Director / Rector')], max_length=20),
        ),
    ]
