# Generated by Django 6.0.4 on 2026-08-16 00:28

import django.db.models.deletion
from django.db import migrations, models


def populate_grados(apps, schema_editor):
    Estudiante = apps.get_model('gestion_colegio', 'Estudiante')
    Grado = apps.get_model('gestion_colegio', 'Grado')

    for estudiante in Estudiante.objects.all():
        nombre = (estudiante.grado or '').strip()
        if nombre:
            grado, _ = Grado.objects.get_or_create(nombre=nombre)
            estudiante.grado_nuevo = grado
            estudiante.save(update_fields=['grado_nuevo'])


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_colegio', '0003_asistencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='estudiante',
            name='grado_nuevo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estudiantes', to='gestion_colegio.grado'),
        ),
        migrations.RunPython(populate_grados, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='estudiante',
            name='grado',
        ),
        migrations.RenameField(
            model_name='estudiante',
            old_name='grado_nuevo',
            new_name='grado',
        ),
    ]
